config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/resume', to: "pages#resume"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AMP-OPS</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/_baocover.html.erb
<div class="baocover">
  <div class="baobckgnd">
    <div class="intro-text text-center">
      <p><span class="aocorekw">Development</span> & <span class="aocorekw">Operation</span> (Build & Support) <span class="aocorekw">Services</span> to provide</p>
    </div>
    <div class="intro-values">
      <div class="introbox-white text-center">
        <p>Immutable Deployments  -  Infrastructure As Code  -  Code to Run Services NOT Pets</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/_coursecards.html.erb
<div class="row">

  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">

    <div class="employment-card">
      <div class="row ecard-header">
          <p>Oct 2006</p>
      </div>
      <div class="ecard-body text-left">
        <p>
          ISEB <br>Foundation in IT Service Management certification
        </p>
      </div>
    </div>

  </div>

  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">

    <div class="employment-card">
      <div class="row ecard-header">
          <p>Sept 2013</p>
      </div>
      <div class="ecard-body text-left">
        <p>
          ORACLE <br>OCA Weblogic Server 11g System Administrator Certification
        </p>
      </div>
    </div>

  </div>

  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">

    <div class="employment-card">
      <div class="row ecard-header">
          <p>Jul 17 - Sep 17</p>
      </div>
      <div class="ecard-body text-left">
        <p>
          LE WAGON <br>Full Stack Developer course
        </p>
      </div>
    </div>

  </div>

</div>

app/views/pages/_employmentcards.html.erb
<div class="row">

  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">

    <div class="employment-card">
      <div class="row ecard-header">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <%= image_tag "employmentcards/mastek.png", {class: "ecardimg-std"}%>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <%= image_tag "employmentcards/homeoffice.png", {class: "ecardimg-std"}%>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-left">
          <p>DEVOPS Engineer <br>Mastek <br>Aug 14 - Mar 17</p>
        </div>
      </div>
      <div class="ecard-body text-left">
        <p>
          Integrated AWS platform using Terraform and
          AWS resources (EC2, ASG, ELB, S3, EBS)<br>
          <br>
          Setup of local test environments using Docker
          and Ansible
          Setup of Zabbix monitoring
          templates for Jboss Fuse<br>
          <br>
          Develop RPMs via maven for automated
          deployments for Postges, Open LDAP, tomcat
          applications.<br>
          <br>
          Setup and maintenance  of Continuous
          Integration Environment using Jenkins,
          Nexus and Puppet<br>
          <br>
          Scripted automation for Jboss Fuse
          product setup and OSGI application deployment
        </p>
      </div>
    </div>

  </div>

  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">

    <div class="employment-card">
      <div class="row ecard-header">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <%= image_tag "employmentcards/atos.png", {class: "ecardimg-std"}%>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <%= image_tag "employmentcards/homeoffice.png", {class: "ecardimg-std"}%>
              <%= image_tag "employmentcards/travelex.png", {class: "ecardimg-std"}%>
              <%= image_tag "employmentcards/nhs.png", {class: "ecardimg-std"}%>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-left">
          <p>Middleware Engineer <br>ATOS <br>June 11 - June 14</p>
        </div>
      </div>
      <div class="ecard-body text-left">
        <p>
          Specialist for UNIX/Middleware environments, deployments in DEV, STAGE, PROD. <br>
          <br>
          Scripted automated deployments and L1/2 operations (ant, jython, perl, shell, java), preparing changes, solving production problems, documentation and wiki updates.<br>
          <br>
          Project resource for installation, configuration and administration of Apache for web servers and reverse proxies, Presentation layer environments running on tomcat and JBOSS, Integration environments using Oracle BPM and OSB and core environments using Weblogic 11g JBOSS specialist for setting up environments using JBOSS EAP.<br>
          <br>
          Configured containers and resources including JMS, JTA, JDBC connection pools, connectors, deployed web services, portal and EJB applications.<br>
          <br>
          Configured containers and resources including JMS, JTA, JDBC connection pools, connectors, deployed web services, portal and EJB applications.
        </p>
      </div>
    </div>

  </div>

  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">

    <div class="employment-card">
      <div class="row ecard-header">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <%= image_tag "employmentcards/cognizant.png", {class: "ecardimg-std"}%>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <%= image_tag "employmentcards/lbg.png", {class: "ecardimg-std"}%>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-left">
          <p>Middleware Engineer <br>Cognizant <br>Oct 09 - Mar 11</p>
        </div>
      </div>
      <div class="ecard-body text-left">
        <p>
          Banking Industry, working for Service Delivery in BAU and Projects team.
          <br>
          <br>
          Creating and configuring Websphere environments, IBM HTTP server, Websphere application server, Oracle Backend, Websphere MQ Messaging. Applying application and product patches.<br>
          <br>
          Management of Source control for environment builds using SCM ClearCase<br>
          <br>
          Wiki page setups, laid out environment builds, deployment procedures and port configurations for JVMs and HTTP servers setup on LPARS in Frames.<br>
          <br>
          Scripting of L1 & 2 operations for BAU service improvements
        </p>
      </div>
    </div>

  </div>

  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">

    <div class="employment-card">
      <div class="row ecard-header">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <%= image_tag "employmentcards/cerner.png", {class: "ecardimg-std"}%>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <%= image_tag "employmentcards/nhs.png", {class: "ecardimg-std"}%>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-left">
          <p>System Engineer <br>Cerner <br>July 06 - July 09</p>
        </div>
      </div>
      <div class="ecard-body text-left">
        <p>
          Healthcare Information Systems Supplier. Consultant of the project implementation. Administrator J2EE application middleware and backend<br>
          <br>
          SDeployed and Supported application patch upgrades and testing<br>
          <br>
          Develop RPMs via maven for automated
          deployments for Postges, Open LDAP, tomcat
          applications.<br>
          <br>
          Presented Knowledge transfer sessions to BAU application support team.<br>
          <br>
          Scripting of deployment of J2EE application using Jython and Websphere
        </p>
      </div>
    </div>

  </div>

  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">

    <div class="employment-card">
      <div class="row ecard-header">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <%= image_tag "employmentcards/cerner.png", {class: "ecardimg-std"}%>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <%= image_tag "employmentcards/nhs.png", {class: "ecardimg-std"}%>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-left">
          <p>Application Support <br>Cerner <br>May 05 - July 06</p>
        </div>
      </div>
      <div class="ecard-body text-left">
        <p>
          Online NHS Appointment Booking system. 3rd line support, presentation code debugging, backend troubleshooting, management of raising and implementing production changes, maintenance of team knowledge base.
        </p>
      </div>
    </div>

  </div>

</div>

app/views/pages/_oskillsgrid.html.erb
<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/redhat.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/aws.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/fabric8.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/git.png", {class: "skillimg-std"}%>
  </div>
</div>

<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/docker.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/puppet.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/oraclewls.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/tomcat.png", {class: "skillimg-std"}%>
  </div>
</div>

<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/jenkins.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/centos.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/zabbix.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/jboss.png", {class: "skillimg-std"}%>
  </div>
</div>

<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/bash.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/ruby.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/python.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/java.png", {class: "skillimg-std"}%>
  </div>
</div>

<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/maven.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/nexus.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/rpm.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= image_tag "skillsgrid/postgres.png", {class: "skillimg-std"}%>
  </div>
</div>

<div class="row">
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    <%= image_tag "skillsgrid/terraform.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    <%= image_tag "skillsgrid/amq.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    <%= image_tag "skillsgrid/camel.png", {class: "skillimg-std"}%>
  </div>
</div>

<div class="row">
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <%= image_tag "skillsgrid/apache.png", {class: "skillimg-std"}%>
  </div>
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <%= image_tag "skillsgrid/haproxy.png", {class: "skillimg-std"}%>
  </div>
</div>

app/views/pages/_overviewcardleft.html.erb
<h1>Anil Patel <span class="aplocation">London, UK</span></h1>

<div class="oseperator-box">
  <div class="oseperator-left">

  </div>
</div>

<p>
  SC cleared DEVOPS engineer with over 10 years experience in using open source and proprietary products to setup environments.<br></br>A professional with an aptitude and will to self-learn new technologies always applying a positive attitude to work as well as the ability to communicate with all areas of business.
</p>

<div class="row aolinks-box text-center">
  <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 aolink-btn">
    <i class="fa fa-github" aria-hidden="true"></i>
    <a href="https://github.com/anilp-ampops">Code</a>
  </div>
  <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 aolinkseperator">
  </div>
  <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 aolink-btn text-center">
    <i class="fa fa-linkedin-square" aria-hidden="true"></i>
    <a href="https://www.linkedin.com/in/anil-patel-8a5ba74/">Work</a>
  </div>
</div>

app/views/pages/_overviewcardright.html.erb
<div class="row">
  <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 aprightgap">

  </div>
  <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 aprightgrid">
    <%= render 'pages/oskillsgrid' %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/nbaocover' %>
<%= render 'pages/baocover' %>

app/views/pages/resume.html.erb
<%= render 'shared/nbresume' %>

<div class="container overview-container">
  <div class="row overview-section">
    <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 overview-left">
      <%= render 'pages/overviewcardleft' %>
    </div>
    <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 overview-right">
      <%= render 'pages/overviewcardright' %>
    </div>
  </div>
</div>

<div class="parallax">
  <div class="parallax-content text-center">
  </div>
</div>

<div class="resume-page text-center">
  <h1>Resume<span class="aplocation"> of Anil Patel</span></h1>
  <div class="container">
    <div class="osep-respage"></div>
  </div>
  <h2>Employment</h2>
  <div class="container">
    <div class="osep-respage"></div>
  </div>
  <div class="container cards-container">
    <%= render 'pages/employmentcards' %>
  </div>
  <h2></h2>
  <div class="container">
    <div class="osep-respage"></div>
  </div>
  <h2>Courses/Certification</h2>
  <div class="container">
    <div class="osep-respage"></div>
  </div>
  <div class="container cards-container">
    <%= render 'pages/coursecards' %>
  </div>
  <h2></h2>
</div

app/views/shared/_nbaocover.html.erb
<div class="aonbcover">
  <div class="aologocover">
    <div class="aologofirst">
      <h1>AMP</h1>
    </div>
    <div class="aologosecond">
      <h1>OPS</h1>
    </div>
  </div>
</div>

app/views/shared/_nbresume.html.erb
<div class="nbresume">
  <div class="nbresume-left">
    <div class="nbresume-link">
      <span><%= link_to "HOME", root_path %></span>
    </div>
    <div class="nbresume-link">
      <span><%= link_to "RESUME", resume_path %></span>
    </div>
  </div>
</div>